import type { Metadata } from 'next';
import './globals.css';
import Providers from '@/components/providers';
import { Dancing_Script } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';
import 'sweetalert2/src/sweetalert2.scss';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const dancingScript = Dancing_Script({
    subsets: ['latin'],
    weight: ['700'],
    preload: true,
    variable: '--font-dancing-script',
    display: 'swap',
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`relative antialiased ${dancingScript.variable}`}>
                <Providers>
                    {children}
                    <Toaster />
                </Providers>
            </body>
        </html>
    );
}
